spring.application.name=banco

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/banco-bitabit
spring.datasource.username=postgres
spring.datasource.password=contrasena

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.kafka.bootstrap-servers=localhost:9092

