spring.application.name=banco

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/banco-bitabit
spring.datasource.username=postgres
spring.datasource.password=contrasena

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.kafka.bootstrap-servers=localhost:9092
# Para ver logs detallados de Camel
logging.level.org.apache.camel=INFO
logging.level.spring.web=INFO

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=observer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer